@startuml

start

if (Token provided?) then (yes)
  :Validate Token;
  
  if (Token valid?) then (yes)
    :Token; <<object>>
    note right
      The token is a jwt token and
      contains the needed information
      (account name, id, email, organization,
      roles, etc.)
    end note
    
    if (Account exists in database?) then (yes)
    else (no)
        :Create account with Identity;
    endif
    
    partition "Update Organizations" {
        while (check organizations ?) is (not finished)
            :Process Organization;
            if (Organization is linked to account?) then (yes)
            else (no)
                :Create Organization-Account Link in Database;
            endif
        endwhile (finished)
    }
    
    :Store account data in
    context;
    note right
      This is required for
      controllers / services to
      be able to access for example
      account / identity id
    end note
  else (no)
    end
  endif
  
else (no)
    end
endif

stop

@enduml
