@startuml
top to bottom direction
skinparam linetype ortho

interface API

package Controller {
    [Identity Controller]
    [Organization Controller]
    [Plan Controller]
    [Scope Controller]
    [Task Controller]
    [WorkSlot Controller]
}

package Service {
    [Account Service]
    [Identity Service]
    [Keycloak Service]
    [Planning Service]
    [Scope Service]
    [Task Service]
    [WorkSlot Service]
}

package Repository {
    [Account Repository]
    [Identity Organization Color Repository]
    [Identity Repository]
    [Identity Settings Repository]
    [Label Repository]
    [Scope Repository]
    [Task Repository]
    [WorkSlot Repository]
}

database MariaDB {

}

cloud Keycloak {
}

Controller --> Service : calls
Service --> Repository : calls
Repository --> Service : returns
Service --> Controller : returns

Repository <-> MariaDB
[Keycloak Service] <--> Keycloak : manages

API <-- Controller

@enduml
