@startuml
top to bottom direction
skinparam linetype ortho

interface API

package Controller {
    [Identity Controller]
    [Plan Controller]
    [Scope Controller]
    [Task Controller]
    [WorkSlot Controller]
}

package Service {
    [Account Service]
    [Identity Service]
    [Planning Service]
    [Scope Service]
    [Task Service]
    [WorkSlot Service]
}

package Repository {
    [Account Repository]
    [Identity Repository]
    [Label Repository]
    [Organization Repository]
    [Scope Repository]
    [Task Dependency Repository]
    [Task Repository]
    [WorkSlot Repository]
}

database MariaDB {

}

Controller --> Service : calls
Service --> Repository : calls
Repository --> Service : returns
Service --> Controller : returns

Repository <-> MariaDB

API <-- Controller

@enduml
