@startchen
skinparam linetype ortho

entity Identity {
    Id: Integer <<key>>
}

entity Account {
    Id: Integer <<key>>
    IdentityId: Integer <<key>>
    OrganizationId: Integer <<key>>
}

entity Organization {
    Id: Integer <<key>>
    Name: String <<key>>
}

entity WorkSlot {
    Id: Integer <<key>>
    AccountId: Integer
    Start: Timestamp <<key>>
    End: Timestamp <<key>>
}

entity Task {
    Id: Integer <<key>>
    AccountId: Integer
    Name: String
    Description: String
    Complexity: Integer
    Time: Integer
    Type: Enum
}

entity TaskDependency {
    Id: Integer <<key>>
    TaskId: Integer <<key>>
    PredecessorId: Integer <<key>>
}

entity Scope {
    Id: Integer <<key>>
    TaskId: Integer <<key>>
    Begin: Timestamp <<key>>
    End: Timestamp <<key>>
}

relationship Linked {
}
Identity -(1,N)- Linked
Linked -(1,1)- Account

relationship "Part Of" as PO {
}
Account -N- PO
PO -1- Organization

relationship "Has" as HasSlot {
}
Account -1- HasSlot
HasSlot -N- WorkSlot

relationship "Has" as HasTask {
}
Account -1- HasTask
HasTask -N- Task

relationship "Depends On" as DO {
}
relationship "Is Predecessor Of" as IPO {
}
TaskDependency -1- DO
DO -N- Task
TaskDependency -1- IPO
IPO -N- Task

relationship "Is split into" as SI {
}
Task -1- SI
SI -N- Scope



@endchen
