@startchen
skinparam linetype ortho

entity Identity {
    Id: Integer <<key>>
}

entity Account {
    Id: Integer <<key>>
    IdentityId: Integer
}

entity Organization {
    Id: Integer <<key>>
    Name: String
}

entity WorkSlot {
    Id: Integer <<key>>
    AccountId: Integer
    StartAt: Timestamp
    EndAt: Timestamp
}

entity Task {
    Id: Integer <<key>>
    AccountId: Integer
    Name: String
    Description: String
    Difficulty: Integer
    StartAt: Timestamp
    EndAt: Timestamp
    DynamicTaskId: Integer
    StaticTaskId: Integer
    RRule: String
}

entity Label {
    Id: Integer <<key>>
    TaskId: Integer
    Name: String
}

entity DynamicTask {
    Id: Integer <<key>>
    Duration: Integer
    Elapsed: Integer
    MinScopeDuration: Integer
    MaxScopeDuration: Integer
}

entity StaticTask {
    Id: Integer <<key>>
    IsBlocker: Boolean
}

entity TaskDependency {
    Id: Integer <<key>>
    DynamicTaskId: Integer
    PredecessorDynamicTaskId: Integer
}

entity Scope {
    Id: Integer <<key>>
    DynamicTaskId: Integer
    StartAt: Timestamp
    EndAt: Timestamp
}

relationship "Is A" as ID {
}
Task -- ID
ID -- DynamicTask

relationship "Is A" as IS {
}
Task -- IS
IS -- StaticTask

relationship Linked {
}
Identity -(1,N)- Linked
Linked -(1,1)- Account

relationship "Part Of" as PO {
}
Account -N- PO
PO -M- Organization

relationship "Has" as HasSlot {
}
Account -1- HasSlot
HasSlot -N- WorkSlot

relationship "Has" as HasLabel {
}
Task -1- HasLabel
HasLabel -N- Label

relationship "Has" as HasTask {
}
Account -1- HasTask
HasTask -N- Task

relationship "Depends On" as DO {
}
relationship "Is Predecessor Of" as IPO {
}
TaskDependency -1- DO
DO -N- DynamicTask
TaskDependency -1- IPO
IPO -N- DynamicTask

relationship "Is split into" as SI {
}
DynamicTask -1- SI
SI -N- Scope



@endchen
