@startchen
skinparam linetype ortho

entity Identity {
    Id: Long <<key>>
}

entity Account {
    Id: Long <<key>>
    Subject: String
    IdentityId: Long
}

entity IdentitySettings {
    Id: Long <<key>>
    IdentityId: Long
    Language: String
    Theme: String
    WorkSettings: JSON
}

entity IdentityOrganizationColor {
    Id: Long <<key>>
    IdentityId: Long
    OrganizationId: String
    Color: ColorToken
}

entity WorkSlot {
    Id: Long <<key>>
    IdentityId: Long
    OrganizationId: String
    DayOfWeek: DayOfWeek
    StartTime: LocalTime
    EndTime: LocalTime
}

entity Task {
    Id: Long <<key>>
    DType: String
    IdentityId: Long
    OrganizationId: String
    Color: ColorToken
    Name: String
    Description: String
    Difficulty: Difficulty
    StartAt: Instant
    EndAt: Instant
}

entity Label {
    Id: Long <<key>>
    TaskId: Long
    Name: String
}

entity DynamicTask {
    Id: Long <<key>>
    Duration: Duration
    Elapsed: Duration
    MinScopeDuration: Duration
    MaxScopeDuration: Duration
}

entity StaticTask {
    Id: Long <<key>>
    RRule: String
    IsBlocker: Boolean
}

entity TaskRelation {
    DependentId: Long <<key>>
    DependencyId: Long <<key>>
}

entity Scope {
    Id: Long <<key>>
    DynamicTaskId: Long
    StartAt: Instant
    EndAt: Instant
}

relationship "Is A" as ID {
}
Task -- ID
ID -- DynamicTask

relationship "Is A" as IS {
}
Task -- IS
IS -- StaticTask

relationship Linked {
}
Identity -(1,N)- Linked
Linked -(1,1)- Account

relationship "Has Settings" as HS {
}
Identity -1- HS
HS -1- IdentitySettings

relationship "Has Color" as HC {
}
Identity -1- HC
HC -N- IdentityOrganizationColor

relationship "Has" as HasSlot {
}
Identity -1- HasSlot
HasSlot -N- WorkSlot

relationship "Has" as HasLabel {
}
Task -1- HasLabel
HasLabel -N- Label

relationship "Has" as HasTask {
}
Identity -1- HasTask
HasTask -N- Task

relationship "Depends On" as DO {
}
TaskRelation -1- DO
DO -N- DynamicTask

relationship "Is Required By" as IRB {
}
TaskRelation -1- IRB
IRB -N- DynamicTask

relationship "Is split into" as SI {
}
DynamicTask -1- SI
SI -N- Scope

@endchen
