@startuml
abstract class Task {
    id : number
    start : Date
    end : Date
    name : string
    description : string
    difficulty : number
    rrule : string
    labels : Label[]
}

class DynamicTask {
    duration : number
    elapsed : number
    minScopeDuration : number
    maxScopeDuration : number
    scopes : Scope[]
    dependencies : DynamicTask[]
}

class StaticTask {
  isBlocker: boolean
}

class Label {
    id : number
    name: string
}

class Scope {
    id: number
    begin: Date
    end: Date
}

Task <|-- DynamicTask
Task <|-- StaticTask
Task --> Label
DynamicTask --> Scope
@enduml
