@startuml
abstract class Task {
    id : number
    identityId : number
    organizationId : string
    color : ColorToken
    startAt : Date
    endAt : Date
    name : string
    description : string
    difficulty : Difficulty
    labels : Label[]
}

class DynamicTask {
    duration : number
    elapsed : number
    minScopeDuration : number
    maxScopeDuration : number
    scopes : Scope[]
    dependencies : number[]
    dependents : number[]
}

class StaticTask {
    rrule : string
    isBlocker : boolean
}

enum ColorToken {
    UNSET
    RED
    ORANGE
    AMBER
    YELLOW
    GREEN
    MINT
    CYAN
    BLUE
    INDIGO
    PURPLE
    PINK
    BROWN
    GRAY
}

enum Difficulty {
    TRIVIAL
    EASY
    MEDIUM
    HARD
    EXTREME
}

class Label {
    id : number
    taskId : number
    name : string
}

class Scope {
    id : number
    dynamicTaskId : number
    startAt : Date
    endAt : Date
}

Task <|-- DynamicTask
Task <|-- StaticTask
Task --> Label
Task --> ColorToken
Task --> Difficulty
DynamicTask --> Scope
DynamicTask --> DynamicTask : dependencies/dependents
@enduml
