@startuml
skinparam classAttributeIconSize 0
skinparam linetype ortho

class identity {
    id: BIGINT <<PK>>
}

class account {
    id: BIGINT <<PK>>
    subject: VARCHAR(255) <<UNIQUE, NOT NULL>>
    identity_id: BIGINT <<FK, NOT NULL>>
}

class identity_settings {
    id: BIGINT <<PK>>
    identity_id: BIGINT <<FK, UNIQUE, NOT NULL>>
    language: VARCHAR(10) <<NOT NULL>>
    theme: VARCHAR(10) <<NOT NULL>>
    work_settings: TEXT
}

class identity_organization_color {
    id: BIGINT <<PK>>
    identity_id: BIGINT <<FK, NOT NULL>>
    organization_id: VARCHAR(255) <<NOT NULL>>
    color: VARCHAR(50) <<NOT NULL>>
    <<UNIQUE(identity_id, organization_id)>>
}

class work_slot {
    id: BIGINT <<PK>>
    identity_id: BIGINT <<FK>>
    organization_id: VARCHAR(255) <<NOT NULL>>
    day_of_week: VARCHAR(10) <<NOT NULL>>
    start_time: TIME <<NOT NULL>>
    end_time: TIME <<NOT NULL>>
}

class task {
    id: BIGINT <<PK>>
    dtype: VARCHAR(31)
    identity_id: BIGINT <<FK>>
    organization_id: VARCHAR(255)
    color: VARCHAR(50) <<NOT NULL>>
    name: VARCHAR(255) <<NOT NULL>>
    description: VARCHAR(255) <<NOT NULL>>
    difficulty: VARCHAR(50) <<NOT NULL>>
    start_at: TIMESTAMP <<NOT NULL>>
    end_at: TIMESTAMP <<NOT NULL>>
}

class label {
    id: BIGINT <<PK>>
    task_id: BIGINT <<FK>>
    name: VARCHAR(255) <<NOT NULL>>
}

class dynamic_task {
    id: BIGINT <<PK, FK>>
    duration: BIGINT <<NOT NULL>>
    elapsed: BIGINT <<NOT NULL>>
    min_scope_duration: BIGINT <<NOT NULL>>
    max_scope_duration: BIGINT <<NOT NULL>>
}

class static_task {
    id: BIGINT <<PK, FK>>
    rrule: VARCHAR(255) <<NOT NULL>>
    is_blocker: BOOLEAN <<NOT NULL>>
}

class task_relation {
    dependent_id: BIGINT <<PK, FK>>
    dependency_id: BIGINT <<PK, FK>>
}

class scope {
    id: BIGINT <<PK>>
    dynamic_task_id: BIGINT <<FK>>
    start_at: TIMESTAMP <<NOT NULL>>
    end_at: TIMESTAMP <<NOT NULL>>
}

task "1" -- "N" label
identity "1" -- "N" account
identity "1" -- "1" identity_settings
identity "1" -- "N" identity_organization_color
identity "1" -- "N" work_slot
identity "1" -- "N" task
scope "N" -- "1" dynamic_task
task_relation "N" -- "1" dynamic_task : dependent
task_relation "N" -- "1" dynamic_task : dependency

task "1" -- "0..1" static_task
task "1" -- "0..1" dynamic_task

@enduml
