@startuml
skinparam classAttributeIconSize 0
skinparam linetype ortho

class identity {
    id: INTEGER
}

class account {
    id: INTEGER
    identity_id: INTEGER
}

class organization {
    id: INTEGER
    name: VARCHAR(64)
}

class account_organization {
    account_id: INTEGER
    organization_id: INTEGER
}

class work_slot {
    id: INTEGER
    account_id: INTEGER
    start: TIMESTAMP
    end: TIMESTAMP
}

class task {
    id: INTEGER
    account_id: INTEGER
    name: VARCHAR(256)
    description: TEXT
    complexity: INTEGER
    time: INTEGER
    type: Enum
}

class task_dependency {
    id: INTEGER
    task_id: INTEGER
    predecessor_task_id: INTEGER
}

class scope {
    id: INTEGER
    task_id: INTEGER
    begin: TIMESTAMP
    end: TIMESTAMP
}

identity "1" -- "N" account
account "1" -- "N" account_organization
account_organization "N" -- "1" organization
work_slot "N" -- "1" account
task "N" -- "1" account
scope "N" -- "1" task
task_dependency "N" -- "1" task : depends
task_dependency "N" -- "1" task : predecessor

@enduml
